# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

version: "{build}"
image: "Visual Studio 2017"
skip_non_tags: true
environment:
  API_VERSION: $(APPVEYOR_REPO_TAG_NAME)
  PASSWORD:
    secure: LcG3EvqYe3nsuUOe6wqviw==
build_script:
  - docker build -t heaths/vssetup:%API_VERSION% .
  - docker tag heaths/vssetup:%API_VERSION% heaths/vssetup:latest
deploy_script:
  - docker login -u heaths -p %PASSWORD%
  - docker push heaths/vssetup:%API_VERSION%
  - docker push heaths/vssetup:latest
